### ISSUE TITLE
Request to Add License

### ISSUE THREAD

**Issue by carceneaux** [rutgerblom/SDDC.Lab#128]
Hi Rutger!

I just found this repo from your blog by Googling `ansible nested esxi host` and you are at the top of the list! I read it over and it looks great! I see a few other posts that I'm interested in as well. All this to say...thanks for sharing! ...and keep up the great work!

Can you please [choose a license](https://choosealicense.com/) and add it to this repo? If a repo doesn't have a license, [this is implied](https://choosealicense.com/no-permission/).

Thanks again!
Chris

**Comment by rutgerblom** [comment]
Thank you and thanks for heads-up regarding the license. We have applied a license now.

Kind regards,
Rutger
